esphome:
  name: esp-mediaplayer-woonkamer

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "28c07fa2e983863568922aa0e1b6c62f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Mediaplayer-Woonkamer"
    password: "RIqjf42j87W2"

captive_portal:

media_player:
  - platform: i2s_audio
    name: Mediaplayer1
    dac_type: external
    i2s_lrclk_pin: GPIO33
    i2s_dout_pin: GPIO22
    i2s_bclk_pin: GPIO19
    mode: mono
